googleauth/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path('', include('googleauthapp.urls')),
]

googleauthapp/urls.py
from django.urls import path
from googleauthapp import views

app_name = "googleauthapp"

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

googleauthapp/models.py
from django.db import models

# Create your models here.

googleauthapp/forms.py
from django import forms

class BookingForm(forms.Form):
    eventTitle = forms.CharField(label="event", max_length=255, required=True)
    startDateTime = forms.DateTimeField(label="startDateTime", input_formats=['%Y/%m/%d %H:%M'], required=True)
    endDateTime = forms.DateTimeField(label="endDateTime", input_formats=['%Y/%m/%d %H:%M'], required=True)

googleauthapp/views.py
from django.shortcuts import render
from django.views.generic import FormView
from googleauthapp.forms import BookingForm
from google.oauth2 import service_account
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from googleapiclient.discovery import build

SCOPES = ["https://www.googleapis.com/auth/calendar"]

service_account_email = "booking-test-service-account@upheld-arena-355505.iam.gserviceaccount.com"
credentials = service_account.Credentials.from_service_account_file('upheld-arena-355505-eafa5172beec.json')
scoped_credentials = credentials.with_scopes(SCOPES)
calendarId = "2010238c4oqlnnm5qsek6rdsks@group.calendar.google.com"


def build_service(request):

    service = build("calendar", "v3", credentials=scoped_credentials)
    return service


class HomeView(FormView):
    form_class = BookingForm
    template_name = 'cal/home.html'

    def post(self, request, *args, **kwargs):
        form = BookingForm(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):

        messages.add_message(self.request, messages.INFO, 'Form submission success!!')
        return reverse('cal:home')

    def form_valid(self, form):

        eventTitle = form.cleaned_data.get("eventTitle")
        start_date_data = form.cleaned_data.get("startDateTime")
        end_date_data = form.cleaned_data.get("endDateTime")

        if start_date_data > end_date_data:
            messages.add_message(self.request, messages.INFO, 'Please enter the correct period.')
            return HttpResponseRedirect(reverse("cal:home"))

        service = build_service(self.request)

        event = (
            service.events().insert(
                calendarId=calendarId,
                body={
                    "summary": eventTitle,
                    "start": {"dateTime": start_date_data.isoformat()},
                    "end": {"dateTime": end_date_data.isoformat()},
                },
            ).execute()
        )

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        form = BookingForm()
        booking_event = []
        service = build_service(self.request)
        events = (
            service.events().list(
                calendarId=calendarId,
            ).execute()
        )

        for event in events['items']:

            event_title = event['summary']

            # Deleted the last 6 characters (deleted UTC time)
            start_date_time = event["start"]["dateTime"]
            start_date_time = start_date_time[:-6]

            # Deleted the last 6 characters (deleted UTC time)
            end_date_time = event['end']["dateTime"]
            end_date_time = end_date_time[:-6]

            booking_event.append([event_title, start_date_time, end_date_time])

        context = {
            "form":form,
            "booking_event" : booking_event,
        }

        return context

googleauthapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
       <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.20/jquery.datetimepicker.css">
    <link rel="stylesheet" href="{% static 'css/custom-style.css' %}">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.20/build/jquery.datetimepicker.full.min.js"></script>
    {% include "cal/js_code.html" %}
</body>
</html>

googleauthapp/templates/cal/home.html
{% extends 'base.html' %} 
{% load googleauthapp %} 
{% block content %}
<h1 class="event_title">Booking Event List</h1>
<div class="event">
  {% for item in booking_event %}
  <ul class="event__list">
    <li>Event title:{{ item.0 }}</li>
    <li>Start_date_time:{{ item.1 }}</li>
    <li>End_date_time:{{ item.2 }}</li>
  </ul>
  {% endfor %}
</div>
<div class="picker">
  <form
    id="picker__confirm"
    class="picker__confirm"
    autocomplete="off"
    action="{% url 'cal:home' %}"
    method="POST"
  >
    {% csrf_token %}
    <div class="picker__component">
      <p class="picker__label">Event name</p>
      {% render_field form.eventTitle class+="picker__field" %}
    </div>
    <div class="picker__component">
      <p class="picker__label">Start Time</p>
      {% render_field form.startDateTime class+="picker__field" %}
    </div>
    <div class="picker__component">
      <p class="picker__label">End Time</p>
      {% render_field form.endDateTime class+="picker__field" %}
    </div>
    <input type="submit" value="Submit" class="picker__button" />
  </form>
</div>
<div class="display_message">
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}>
      {{ message }}
    </li>
    {% endfor %}
  </ul>
  {% endif %}
</div>
{% endblock %}

googleauthapp/templates/cal/js_code.html
<script>
  $(function () {
    $("#id_startDateTime").datetimepicker({});
    $("#id_endDateTime").datetimepicker({});
  });
</script>